# Generated by Django 3.2 on 2021-04-16 04:50

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc
import home.utilities


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_auto_20210416_0215'),
    ]

    operations = [
        migrations.CreateModel(
            name='AK',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=250, verbose_name='Заголовок')),
                ('slug', models.SlugField(max_length=250, unique_for_date='publish')),
                ('content', models.TextField(verbose_name='Содержание')),
                ('image', models.ImageField(blank=True, upload_to=home.utilities.get_timestamp_path, verbose_name='Изображение')),
                ('is_active', models.BooleanField(db_index=True, default=True, verbose_name='Выводить в списке?')),
                ('publish', models.DateTimeField(default=datetime.datetime(2021, 4, 16, 4, 50, 34, 640857, tzinfo=utc))),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('published', 'Published')], default='draft', max_length=10)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Автор')),
                ('rubric', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='home.subrubric', verbose_name='Рубрика')),
            ],
            options={
                'ordering': ('-publish',),
            },
        ),
        migrations.CreateModel(
            name='AdditionalImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to=home.utilities.get_timestamp_path, verbose_name='Изображение')),
                ('ak', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.ak', verbose_name='Запись')),
            ],
            options={
                'verbose_name': 'Дополнительная иллюстрация',
                'verbose_name_plural': 'Дополнительные иллюстрации',
            },
        ),
    ]
