# Generated by Django 3.2 on 2021-04-28 20:37

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_alter_ak_publish'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ak',
            name='publish',
            field=models.DateTimeField(default=datetime.datetime(2021, 4, 28, 20, 37, 2, 149286, tzinfo=utc)),
        ),
    ]
