# Generated by Django 3.2 on 2021-04-29 20:36

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0006_alter_ak_publish'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ak',
            name='publish',
            field=models.DateTimeField(default=datetime.datetime(2021, 4, 29, 20, 36, 8, 497481, tzinfo=utc)),
        ),
    ]
